Repository MyPureCloud/genesys-spark, pull requests merged in 2024-02, with the labels that each got.

#294 feat(phone-input): phone input restyle for v4
  packages/genesys-spark-components/src/components/beta/gux-flag-icon/gux-flag-icon.scss
  packages/genesys-spark-components/src/components/beta/gux-phone-input/gux-phone-input.scss
  packages/genesys-spark-components/src/components/beta/gux-phone-input/gux-phone-input.tsx
  packages/genesys-spark-components/src/components/beta/gux-phone-input/tests/gux-phone-input.e2e.ts
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-phone/example.html
  packages/genesys-spark-components/src/components/stable/gux-form-field/components/gux-form-field-phone/gux-form-field-phone.scss
  packages/genesys-spark-tokens/data/tokens.json
  packages/genesys-spark-tokens/snapshot/css/gse-ui-formsAndInputs.css
  packages/genesys-spark-tokens/snapshot/json/gse-ui-formsAndInputs.json
  packages/genesys-spark-tokens/snapshot/less/gse-ui-formsAndInputs.less
  packages/genesys-spark-tokens/snapshot/scss/_gse-ui-formsAndInputs.scss
Labels: UX Review Wanted

#323 fix(datepicker): fixed font size bug
  packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.less
Labels: backport

#309 feat(accordion): added open and close events
  packages/genesys-spark-components/src/components/stable/gux-accordion/example.html
  packages/genesys-spark-components/src/components/stable/gux-accordion/gux-accordion-section/gux-accordion-section.tsx
  packages/genesys-spark-components/src/components/stable/gux-accordion/gux-accordion-section/readme.md
  packages/genesys-spark-components/src/components/stable/gux-accordion/gux-accordion.tsx
Labels: api change

#346 fix(time-picker-beta): AM/PM button does not inherit visibility css property when set on component
  packages/genesys-spark-components/src/components/beta/gux-time-picker/gux-time-picker.less
Labels: backport
