Repository MyPureCloud/genesys-spark, pull requests merged in 2024-07, with the labels that each got.

#336 feat(time-zone-picker): allow custom defaults
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/example.html
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/gux-time-zone-picker.tsx
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/i18n/en.json
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/readme.md
  packages/genesys-spark-components/src/components/beta/gux-time-zone-picker/tests/gux-time-zone-picker.spec.ts
  packages/genesys-spark-components/src/components/stable/gux-list/gux-list-divider/readme.md
  packages/genesys-spark-components/src/components/stable/gux-listbox/option-group/readme.md
  packages/genesys-spark-components/src/i18n/translations/en.json
Labels: api change

#541 fix(datepicker): ensure format is set before updating date
  packages/genesys-spark-components/src/components/stable/gux-datepicker/gux-datepicker.tsx
Labels: backport

#547 fix(pagination-beta): filter out characters from slotted number input
  packages/genesys-spark-components/src/components/beta/gux-pagination-beta/gux-pagination-buttons-beta/gux-pagination-ellipsis-button/gux-pagination-ellipsis-button.tsx
Labels: backport

#539 fix(flyout-menu): Fix menu arrow position
  packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-flyout-menu.scss
  packages/genesys-spark-components/src/components/stable/gux-flyout-menu/gux-flyout-menu.tsx
  packages/genesys-spark-components/src/components/stable/gux-flyout-menu/tests/__snapshots__/gux-flyout-menu.spec.ts.snap
Labels: UX Review Wanted

#556 feat(icon): add redo, undo, eraser, grid-2-plus and link-simple icons to v3
  packages/genesys-spark-components/src/components/stable/gux-icon/gux-icon.types.ts
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/custom/redo-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/custom/undo-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/eraser-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/grid-2-plus-regular.svg
  packages/genesys-spark-components/src/components/stable/gux-icon/icons/fa/link-simple-regular.svg
  web-apps/genesys-spark-examples/src/utils/generateFontAwesomeIcons.js
Labels: backport
